# Generated by Django 4.0.5 on 2022-06-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='funcional',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='nombre',
            field=models.TextField(max_length=10),
        ),
    ]
