# Generated by Django 4.0.5 on 2022-06-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_dispositivo_funcional_alter_dispositivo_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='marca',
            field=models.CharField(default='unknown', max_length=10),
        ),
    ]
