# Generated by Django 4.0.5 on 2022-06-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='donador',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='apellidos',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombres',
            field=models.TextField(max_length=30),
        ),
    ]
